[package]
name = "code-search"
version = "0.3.3"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#tokio = { version = "1.10", features = ["full"] }
term_size = "0.3"
